services:
  - type: web
    name: mystory-express
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /healthz
    runtime: node
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      # ถ้ามี SECRET อื่น ๆ ใส่เพิ่มที่นี่
